### PR TITLE
fix for bnc919061

### PR DESCRIPTION
**Pull request by kmroz**
Rebased [pull#38](https://github.com/yast/yast-nfs-client/pull/38) against SLE-12-GA branch, and added a couple extra bits per discussion with ancorgs.

### CODE REVIEW

**Comment by ancorgs** [comment]
LGTM, let's wait for travis

**Comment by kmroz** [comment]
Errno::ETIMEDOUT: Connection timed out - connect(2) for "api.rubygems.org" port 443 (https://api.rubygems.org/api/v1/dependencies?gems=rspec-core)

bleh!

**Comment by ancorgs** [comment]
Thanks.

**Comment by kmroz** [comment]
Happy to help.

**Pull request merged**
