### PR TITLE
ui: fix block local scope for certain variables

### PR DESCRIPTION
**Pull request by kmroz**

### CODE REVIEW

**Comment by mvidner** [comment]
Oh, thanks!
Apparently I have introduced the bug in edc759bf4a82b175e6c1bbd1360a35249a5a71d2 when I replaced

```ruby
begin
  ...
end while cond
```

with

```ruby
loop do
   ...
   break unless cond
end
```

to please Rubocop: Lint/Loop.

**Comment by kmroz** [comment]
No problem, happy we caught it :)

**Comment by ancorgs** [comment]
@kmroz Could you please increase the version number in yast2-nfs-client.spec and add an entry in yast2-nfs-client.changes so I can merge?

It would be even better (although not mandatory) if, in addition to that, you could "redirect" the pull request to the SLE-12-GA branch (that's supposed to be the healthier order, first old branch and then merge to master).

**Comment by ancorgs** [comment]
@kmroz btw, please mention bug#919061 in the changelog.

**Comment by kmroz** [comment]
@ancorgs Will take care of that this morning. Thanks!

**Comment by kmroz** [comment]
As per above, closing this PR to re-open against SLE-12-GA branch

**Pull request closed without merging**
